### ISSUE TITLE
Question about ‘head-cls’ type

### ISSUE THREAD

**Issue by ofishhaha** [ggjy/DeFeat.pytorch#13]
Thank u for ur great efforts. I noticed there is a head-cls distillation type in ur source code.
I tried to use this type with setting 'head-cls, KL-decouple' in the config. But the acc get much lower（70% for AP50） than the original student model.

Do u have any recommend settings and hyperparameters of the 'head-cls' type? thanks

**Comment by dnty** [comment]
请问decouple的config里有用到对分类分支（head-cls）的蒸馏吗？

**Comment by ggjy** [comment]
I don't use the head-cls. I found that the boost from head-cls is limited, sometimes you can do the grid search to find the best weight for head-cls, but it can only bring about 0.1-0.2% improvement. So I don't use the head-cls in our paper.
