### ISSUE TITLE
请教作者，请问论文中中间层特征的蒸馏损失，在代码的哪些部分?

### ISSUE THREAD

**Issue by ratcat1232** [ggjy/DeFeat.pytorch#17]
作者您好，感谢您所贡献的代码和论文。想请教一下论文中提到的有关解耦目标和背景的中间层特征蒸馏损失，这部分大概在代码的哪部分。能否指教一下？

**Comment by ggjy** [comment]
可以参考[这里](https://github.com/ggjy/DeFeat.pytorch/blob/main/mmdet/apis/train.py#L299)
