### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by waveboo** [ggjy/DeFeat.pytorch#20]
Hi @ggjy,
When I read the code about the 'decoupled-cls'. I have some problems with the code.

[Here](https://github.com/ggjy/DeFeat.pytorch/blob/main/mmdet/apis/train.py#L262), the 'KL-decouple' uses the labels to distinguish the positive and negative samples. The labels are from the student's bbox_targets [here](https://github.com/ggjy/DeFeat.pytorch/blob/main/mmdet/apis/train.py#L211). It is generated by the student's proposals. But the 'cls_score_s' and 'cls_score_t' are [here](https://github.com/ggjy/DeFeat.pytorch/blob/main/mmdet/apis/train.py#L223) that use the student model and the teacher model to forward the teacher's proposals(sampling_results). 

**So I'm wondering if there exists any mismatch because the cls_scores are from the teacher's proposals while the labels are from the student's proposals.**

Looking forward to your reply, thanks~

**Comment by waveboo** [comment]
Meanwhile, I do not find any setting of freezing model_t. Does the model_t optimize with the student model together?

**Comment by ggjy** [comment]
Hi, for your first quesiton, you are right, it should be ```head_det_t['bbox_targets']```. The setting of freezing model_t can be found [here](https://github.com/ggjy/DeFeat.pytorch/blob/c46a793df414a42f64f9fad9c7106ee60b44c9b3/tools/train_kd.py#L191).

**Comment by waveboo** [comment]
Fine, thanks for your reply.
