### ISSUE TITLE
libcudart.so.10.0:cannot open shared object file

### ISSUE THREAD

**Issue by gear106** [ggjy/DeFeat.pytorch#3]
您好，我按照要求安装了python3.6, pytorch1.5, mmdet2.0.0, mmcv0.5.6,cuda10.1 ，为啥报错libcudart.so.10.0:cannot open shared object file？

**Comment by ggjy** [comment]
你有把我文件中的mmcv软连接删除么？`https://github.com/ggjy/DeFeat.pytorch/blob/main/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so` 我是从mmcv的源文件`.tar.gz`编译然后再把编译好的mmcv包`mv`过去的。编译好和mmdet2.0适配的mmcv，能跑起来mmdetection即可。

**Comment by gear106** [comment]
您好，我是直接下载您的源文件后解压后python setup.py install 安装了mmdet2.0,  然后pip安装的mmcv0.5.6, 您的意思是不用再手动安装mmcv吗？

**Comment by ggjy** [comment]
那应该不用了，你直接把我文件夹下的mmcv删除就行了。

**Comment by gear106** [comment]
您好，我删除您文件夹下的mmcv提示还是这个问题？请问大概是哪里安装版本适配有问题吗？

**Comment by ggjy** [comment]
这个错还是mmcv的问题，我建议你可以试试以下两种方法：

-1- clone我的文件后，删除mmcv，先进行mmcv的安装，再`cd DeFeat.pytorch` 和 `pip install -v -e .`

-2- 我是去下载mmcv源码`https://pypi.org/project/mmcv/0.5.6/` 然后install from source，最后`cd DeFeat.pytorch` 和 `pip install -v -e .`

**Comment by gear106** [comment]
您好，感谢您的留言，根据您的意见采用方法1解决了上述问题，但
在跑您源代码时/DeFeat.pytorch/mmdet/apis/train.py中 from mmcv.runner import Runner_kd,  出现ImportError: cannot import name 'Runner_kd',这个是什么问题呢？我试了下mmcv中好像没有没有Runner_kd这个函数？

**Comment by ggjy** [comment]
当时跑实验的时候为了方便我直接改了mmcv里面的部分函数(`https://github.com/ggjy/DeFeat.pytorch/blob/main/mmcv/runner/runner_kd.py#L303`)来实现蒸馏的效果，如果你想直接用我代码里面的蒸馏代码最快捷的方法是从source编译mmcv，这样可以直接像我一样改mmcv的代码，或者你可以稍微重构一下我的代码而不去更改mmcv里面的函数。

**Comment by gear106** [comment]
明白了，谢谢您

**Comment by pummi823** [comment]
求问具体改了哪些函数 咋改回去呀？

**Comment by pummi823** [comment]
可以具体说一下怎样“稍微重构”您的代码吗T T

**Comment by Lhj-cd** [comment]
> 明白了，谢谢您

请问下从source编译mmcv是怎么个编译法？我也遇到了ImportError: cannot import name 'Runner_kd'，请问您是怎么解决的？万分感谢！

**Comment by Lhj-cd** [comment]
> 当时跑实验的时候为了方便我直接改了mmcv里面的部分函数(`https://github.com/ggjy/DeFeat.pytorch/blob/main/mmcv/runner/runner_kd.py#L303`)来实现蒸馏的效果，如果你想直接用我代码里面的蒸馏代码最快捷的方法是从source编译mmcv，这样可以直接像我一样改mmcv的代码，或者你可以稍微重构一下我的代码而不去更改mmcv里面的函数。

请问下从source编译mmcv是怎么个编译法？我也遇到了ImportError: cannot import name 'Runner_kd'，请问具体是怎么解决？万分感谢！

**Comment by yuhua666** [comment]
> > 当时跑实验的时候为了方便我直接改了mmcv里面的部分函数(`https://github.com/ggjy/DeFeat.pytorch/blob/main/mmcv/runner/runner_kd.py#L303`)来实现蒸馏的效果，如果你想直接用我代码里面的蒸馏代码最快捷的方法是从source编译mmcv，这样可以直接像我一样改mmcv的代码，或者你可以稍微重构一下我的代码而不去更改mmcv里面的函数。
> 
> 请问下从source编译mmcv是怎么个编译法？我也遇到了ImportError: cannot import name 'Runner_kd'，请问具体是怎么解决？万分感谢！

抱歉，我还有相同的问题，可以为我解答吗？
